// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: step6.proto

//package generated6.protocol;

package generated6

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyMessage) Reset() {
	*x = MyMessage{}
	mi := &file_step6_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMessage) ProtoMessage() {}

func (x *MyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_step6_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMessage.ProtoReflect.Descriptor instead.
func (*MyMessage) Descriptor() ([]byte, []int) {
	return file_step6_proto_rawDescGZIP(), []int{0}
}

func (x *MyMessage) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MyMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MyMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MyMessage           `protobuf:"bytes,1,rep,name=Messages,proto3" json:"Messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyMessageList) Reset() {
	*x = MyMessageList{}
	mi := &file_step6_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMessageList) ProtoMessage() {}

func (x *MyMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_step6_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMessageList.ProtoReflect.Descriptor instead.
func (*MyMessageList) Descriptor() ([]byte, []int) {
	return file_step6_proto_rawDescGZIP(), []int{1}
}

func (x *MyMessageList) GetMessages() []*MyMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_step6_proto protoreflect.FileDescriptor

const file_step6_proto_rawDesc = "" +
	"\n" +
	"\vstep6.proto\x12\n" +
	"generated6\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\tMyMessage\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"B\n" +
	"\rMyMessageList\x121\n" +
	"\bMessages\x18\x01 \x03(\v2\x15.generated6.MyMessageR\bMessages2\x85\x01\n" +
	"\bStep6RPC\x127\n" +
	"\x04Save\x12\x15.generated6.MyMessage\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\tGetLast10\x12\x16.google.protobuf.Empty\x1a\x19.generated6.MyMessageList\"\x00B\x0eZ\f./generated6b\x06proto3"

var (
	file_step6_proto_rawDescOnce sync.Once
	file_step6_proto_rawDescData []byte
)

func file_step6_proto_rawDescGZIP() []byte {
	file_step6_proto_rawDescOnce.Do(func() {
		file_step6_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_step6_proto_rawDesc), len(file_step6_proto_rawDesc)))
	})
	return file_step6_proto_rawDescData
}

var file_step6_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_step6_proto_goTypes = []any{
	(*MyMessage)(nil),     // 0: generated6.MyMessage
	(*MyMessageList)(nil), // 1: generated6.MyMessageList
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_step6_proto_depIdxs = []int32{
	0, // 0: generated6.MyMessageList.Messages:type_name -> generated6.MyMessage
	0, // 1: generated6.Step6RPC.Save:input_type -> generated6.MyMessage
	2, // 2: generated6.Step6RPC.GetLast10:input_type -> google.protobuf.Empty
	2, // 3: generated6.Step6RPC.Save:output_type -> google.protobuf.Empty
	1, // 4: generated6.Step6RPC.GetLast10:output_type -> generated6.MyMessageList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_step6_proto_init() }
func file_step6_proto_init() {
	if File_step6_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_step6_proto_rawDesc), len(file_step6_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_step6_proto_goTypes,
		DependencyIndexes: file_step6_proto_depIdxs,
		MessageInfos:      file_step6_proto_msgTypes,
	}.Build()
	File_step6_proto = out.File
	file_step6_proto_goTypes = nil
	file_step6_proto_depIdxs = nil
}
